"""페이지 파일과 README 인덱스 관리. Notion ID로 기존 파일을 식별합니다."""

import json
import os
import re
import tempfile
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from urllib.parse import quote, urlsplit
from uuid import UUID

from .constants import (
    DEFAULT_PAGE_TITLE,
    ISO_DATE_LENGTH,
    README_FILENAME,
    RELATIVE_URL_SAFE,
    TIL_DIRECTORY,
)
from .markdown import escape_markdown

MAX_TITLE_BYTES = 180
HEADER_SCAN_LINES = 12
TITLE_FILENAME_OFFSET = ISO_DATE_LENGTH + len("_")
NOTION_PAGE_HOSTS = frozenset(
    {"notion.so", "www.notion.so", "notion.com", "www.notion.com", "app.notion.com"}
)

MARKER_START = "<!-- TIL_LIST_START -->"
MARKER_END = "<!-- TIL_LIST_END -->"
DEFAULT_README_TEMPLATE = f"""# 📝 My TIL (Today I Learned)

> 매일매일 학습한 내용을 노션에 기록하고, GitHub Actions를 통해 자동으로 동기화하는 저장소입니다. 🚀

<div align="center">
  <img src="https://img.shields.io/badge/Notion-000000?style=for-the-badge&logo=notion&logoColor=white" />
  <img src="https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white" />
</div>

<br/>

## 📚 TIL 기록 목록

{MARKER_START}
{MARKER_END}

---
<p align="center"><i>Auto-generated by <b>GitHub Actions</b> & <b>Notion API</b></i></p>
"""


def atomic_write_text(path: Path, content: str) -> bool:
    """완성된 UTF-8 파일만 교체하고 동일한 내용은 다시 쓰지 않습니다."""
    data = content.encode("utf-8")
    if path.exists() and path.read_bytes() == data:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(data)
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    return True


def sanitize_filename(title: str) -> str:
    # Linux의 255-byte 파일명 제한도 지킵니다. 접미사와 확장자 공간을 남깁니다.
    cleaned = re.sub(r'[\\/*?:"<>|\x00-\x1f\x7f]', "", title)
    cleaned = re.sub(r"\s", "_", cleaned).strip(". ")
    cleaned = cleaned.encode("utf-8")[:MAX_TITLE_BYTES].decode("utf-8", errors="ignore")
    return cleaned.rstrip(". ") or DEFAULT_PAGE_TITLE


def page_id_from_header(header: str) -> str | None:
    marker = re.search(r"<!-- notion-page-id: ([0-9a-f-]+) -->", header)
    if marker:
        try:
            return UUID(marker.group(1)).hex
        except ValueError:
            return None
    source = re.search(
        r"^> 원본 노션: \[링크\]\((https?://[^\s)]+)\)", header, re.MULTILINE
    )
    if source:
        parsed = urlsplit(source.group(1))
        if parsed.hostname not in NOTION_PAGE_HOSTS:
            return None
        match = re.search(
            r"([0-9a-f]{32}|[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12})$",
            parsed.path,
            re.IGNORECASE,
        )
        if match:
            return UUID(match.group(1)).hex
    return None


@dataclass(frozen=True)
class Entry:
    path: Path
    date: date
    title: str
    page_id: str | None


def scan_entries(til_dir: Path) -> list[Entry]:
    entries = []
    # 첨부된 .md 파일은 학습 기록으로 오인하지 않습니다.
    for path in sorted(til_dir.glob("[0-9][0-9][0-9][0-9]/[0-9][0-9]/*.md")):
        if not re.match(r"\d{4}-\d{2}-\d{2}_.+\.md$", path.name):
            continue
        try:
            entry_date = date.fromisoformat(path.name[:ISO_DATE_LENGTH])
        except ValueError:
            continue
        with path.open(encoding="utf-8") as handle:
            header = "".join(handle.readline() for _ in range(HEADER_SCAN_LINES))
        title = path.stem[TITLE_FILENAME_OFFSET:].replace("_", " ")
        metadata = re.search(r"^<!-- notion-title: (.+) -->$", header, re.MULTILINE)
        if metadata:
            parsed_title = json.loads(metadata.group(1))
            if isinstance(parsed_title, str):
                title = parsed_title
        else:
            heading = re.search(r"^# (.+)$", header, re.MULTILINE)
            if heading:
                title = heading.group(1)
        entries.append(Entry(path, entry_date, title, page_id_from_header(header)))
    return entries


class PageStore:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.til_dir = root / TIL_DIRECTORY
        self.entries = scan_entries(self.til_dir)

    def path_for(self, page_id: str, title: str, date_str: str) -> Path:
        page_key = UUID(page_id).hex
        parsed_date = date.fromisoformat(date_str)
        directory = self.til_dir / f"{parsed_date.year:04}" / f"{parsed_date.month:02}"
        path = directory / f"{date_str}_{sanitize_filename(title)}.md"
        owners = {str(entry.path).casefold(): entry.page_id for entry in self.entries}
        key = str(path).casefold()
        if (key in owners and owners[key] != page_key) or (
            path.exists() and key not in owners
        ):
            path = directory / f"{date_str}_{sanitize_filename(title)}_{page_key}.md"
            key = str(path).casefold()
            if (key in owners and owners[key] != page_key) or (
                path.exists() and key not in owners
            ):
                raise ValueError(f"다른 파일과 경로가 충돌합니다: {path}")
        return path

    def save(
        self,
        page_id: str,
        title: str,
        date_str: str,
        page_url: str,
        body: str,
        path: Path,
    ) -> bool:
        page_key = UUID(page_id).hex
        # JSON 문자열로 원래 제목(밑줄, 대괄호 등)을 보관합니다.
        title_json = json.dumps(title, ensure_ascii=False).replace(
            "-->", "\\u002d\\u002d>"
        )
        display_title = title.replace("\n", " ").replace("\r", " ")
        content = (
            f"# {escape_markdown(display_title)}\n\n"
            f"> 날짜: {date_str}\n> 원본 노션: [링크]({page_url})\n\n"
            f"<!-- notion-page-id: {page_key} -->\n"
            f"<!-- notion-title: {title_json} -->\n\n---\n\n{body.rstrip()}\n"
        )
        changed = atomic_write_text(path, content)
        for entry in self.entries:
            # 경로는 TIL 스캔에서 얻은 같은 Notion 페이지 파일만 허용합니다.
            if (
                entry.page_id == page_key
                and entry.path != path
                and entry.path.resolve().is_relative_to(self.til_dir.resolve())
            ):
                entry.path.unlink(missing_ok=True)
                changed = True
        self.entries = [entry for entry in self.entries if entry.page_id != page_key]
        self.entries.append(Entry(path, date.fromisoformat(date_str), title, page_key))
        return changed


def build_index(entries: list[Entry], readme_dir: Path) -> str:
    grouped: dict[str, list[Entry]] = {}
    for entry in sorted(
        entries, key=lambda e: (-e.date.toordinal(), e.title, e.path.as_posix())
    ):
        grouped.setdefault(entry.date.strftime("%Y년 %m월"), []).append(entry)
    parts = []
    for index, (month, items) in enumerate(grouped.items()):
        if index == 0:
            parts.append(f"### 💡 {month}\n\n")
        else:
            parts.append(
                f"<details>\n<summary>📂 {month} ({len(items)}개의 기록)</summary>\n\n"
            )
        for entry in items:
            relative = Path(os.path.relpath(entry.path, readme_dir)).as_posix()
            link = quote(relative, safe=RELATIVE_URL_SAFE)
            label = escape_markdown(entry.title.replace("\n", " ").replace("\r", " "))
            parts.append(f"- 🗓️ **{entry.date:%Y.%m.%d}** | 🔗 [{label}](./{link})\n")
        parts.append("\n" if index == 0 else "\n</details>\n\n")
    return "".join(parts)


def update_readme(root: Path, *, reset: bool = False) -> bool:
    path = root / README_FILENAME
    original = (
        DEFAULT_README_TEMPLATE
        if reset or not path.exists()
        else path.read_text(encoding="utf-8")
    )
    start = original.find(MARKER_START)
    end = original.find(MARKER_END)
    if start == -1 and end == -1:
        # 사용자 설명을 덮어쓰지 않고 자동 생성 영역을 뒤에 붙입니다.
        original = (
            original.rstrip()
            + f"\n\n## 📚 TIL 기록 목록\n\n{MARKER_START}\n{MARKER_END}\n"
        )
        start, end = original.find(MARKER_START), original.find(MARKER_END)
    if (
        start < 0
        or end < start
        or original.count(MARKER_START) != 1
        or original.count(MARKER_END) != 1
    ):
        raise ValueError(
            "README의 TIL_LIST_START/END 마커 쌍을 확인하세요. 기존 내용은 보존했습니다."
        )
    index = build_index(scan_entries(root / TIL_DIRECTORY), path.parent)
    content = original[: start + len(MARKER_START)] + "\n" + index + original[end:]
    return atomic_write_text(path, content)
